plugins:
  - path: .yarn/plugins/yarn-plugin-tsconfig.cjs
    spec: "./.yarn/plugins/yarn-plugin-tsconfig.cjs"

nodeLinker: node-modules

tsconfigPaths:
  "@shangxueink/koishi-plugin-puppeteer-without-canvas": 
    - "./external/puppeteer-without-canvas/src"
